In [1]:
# Creates ndarray 
import numpy as np

In [2]:
a1=np.array([1,2,3])

In [3]:
a1

array([1, 2, 3])

In [4]:
a2=np.array([[1,2,3],[4,5,6]])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
a3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [6]:
type(a1),type(a2),type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [7]:
a1.shape,a2.shape,a3.shape

((3,), (2, 3), (3, 2, 3))

In [8]:
a1.dtype,a2.dtype,a3.dtype

(dtype('int64'), dtype('int64'), dtype('int64'))

In [9]:
a1.size,a2.size,a3.size

(3, 6, 18)

# Creating DATAFRAME by using numpy ndarray

In [10]:
import pandas as pd
pd.DataFrame(a2)

0  1  2
0  1  2  3
1  4  5  6

In [11]:
np.array(["fs","SDf","sd"])

array(['fs', 'SDf', 'sd'], dtype='<U3')

In [12]:
data=np.ones((2,3),dtype="int")

In [13]:
data

array([[1, 1, 1],
       [1, 1, 1]])

In [14]:
zeros=np.zeros((3,3,3),dtype="int")
zeros

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

In [15]:
range_arr=np.arange(2,21,2)
range_arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [16]:
random_arr=np.random.randint(1,22,(3,2,6,4))
random_arr

array([[[[13,  5,  7, 21],
         [ 7,  2,  9,  4],
         [ 7, 10,  7, 15],
         [10, 12,  5, 12],
         [ 7, 15, 21, 16],
         [10, 17,  9, 19]],

        [[16,  1, 18, 13],
         [17, 10,  4,  7],
         [10, 10,  4,  1],
         [ 9,  7,  2,  8],
         [20, 12,  1, 11],
         [14, 19,  9,  4]]],


       [[[21, 12,  9, 14],
         [ 3, 20, 14,  5],
         [12,  3,  3, 15],
         [ 6,  1,  7, 17],
         [ 8, 10, 18,  1],
         [ 4,  7, 14,  3]],

        [[18, 15, 12, 21],
         [ 4,  3, 20,  2],
         [18, 16, 14,  6],
         [20, 11, 15, 19],
         [18,  5, 18, 10],
         [13, 19,  1,  7]]],


       [[[13, 12, 17, 15],
         [ 1, 18,  2, 10],
         [10, 21, 15, 15],
         [12, 14, 13,  9],
         [10, 16, 16, 10],
         [ 9, 13, 17, 15]],

        [[14, 14, 11, 21],
         [16,  2,  5, 20],
         [ 3, 21, 13, 19],
         [15, 10, 12,  8],
         [ 3, 13,  9,  1],
         [13, 10, 15, 18]]]])

In [17]:
random_arr2=np.random.random((3,3,2))
random_arr2

array([[[0.83788329, 0.50137899],
        [0.79741344, 0.82418448],
        [0.49169121, 0.03881241]],

       [[0.06124252, 0.70013262],
        [0.75832666, 0.2276484 ],
        [0.34059652, 0.22193817]],

       [[0.19670765, 0.80182116],
        [0.54778427, 0.60121712],
        [0.49153342, 0.78437017]]])

In [18]:
random_arr3=np.random.rand(2,3,3)
random_arr3

array([[[0.55573118, 0.09063671, 0.19474026],
        [0.45889495, 0.28443224, 0.79248032],
        [0.66080348, 0.56384123, 0.65952271]],

       [[0.86397618, 0.18040713, 0.53051387],
        [0.12470147, 0.42690243, 0.84361406],
        [0.45079891, 0.36959553, 0.85219214]]])

In [19]:
np.random.seed(0)
d=np.random.randint(10,size=(3,5),dtype="int")
d

array([[5, 0, 3, 3, 7],
       [9, 3, 5, 2, 4],
       [7, 6, 8, 8, 1]])

In [20]:
np.random.seed(0)
d=np.random.randint(10,size=(3,5))
d

array([[5, 0, 3, 3, 7],
       [9, 3, 5, 2, 4],
       [7, 6, 8, 8, 1]])

In [21]:
np.unique(d)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
a1=np.array([1,2,4])

In [23]:
a2=np.random.randint(1,9,(3,2))

In [24]:
a2

array([[7, 8],
       [8, 7],
       [1, 2]])

In [25]:
a3=[2,3]

In [26]:
a2*a3

array([[14, 24],
       [16, 21],
       [ 2,  6]])

In [27]:
np.dot(a1,a2)

array([27, 30])

#Use Python methods(`sum()`) on python datatypes
use Numpy methods (`np.sum()`) on numpy datatypes Chaitanya kumar gunuru chaitanya kumar 

In [28]:
np.sum(a2)

33

In [29]:
sum(a2)

array([16, 17])

In [30]:
%timeit np.sum(np.random.random(10000))

67.2 µs ± 31.8 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [31]:
%timeit sum(np.random.random(10000))

903 µs ± 6.61 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


Reshaping and Transposing

In [32]:
np.random.seed(0)
a1=np.random.randint(21,size=(3,5))
a1

array([[12, 15,  0,  3,  3],
       [ 7,  9, 19, 18,  4],
       [ 6, 12,  1,  6,  7]])

In [33]:
a1.reshape(5,3,1)

array([[[12],
        [15],
        [ 0]],

       [[ 3],
        [ 3],
        [ 7]],

       [[ 9],
        [19],
        [18]],

       [[ 4],
        [ 6],
        [12]],

       [[ 1],
        [ 6],
        [ 7]]])

In [34]:
#TRANSPOSE
a1.T

array([[12,  7,  6],
       [15,  9, 12],
       [ 0, 19,  1],
       [ 3, 18,  6],
       [ 3,  4,  7]])

In [35]:
import pandas as pd

In [36]:
# creating dataframes for np operation
weekly_sales=pd.DataFrame(a1.T,index=["mon","tue","wed","thur","fri"],columns=["almonds","peanut","cashewnut"])

In [37]:
weekly_sales

almonds  peanut  cashewnut
mon        12       7          6
tue        15       9         12
wed         0      19          1
thur        3      18          6
fri         3       4          7

In [38]:
prices=np.array([20,10,25])
prices

array([20, 10, 25])

In [39]:
prices=prices.reshape(1,3)
prices

array([[20, 10, 25]])

In [40]:
nuts_prices=pd.DataFrame(prices,index=["price"],columns=["almonds","peanut","cashewnut"])

In [41]:
nuts_prices

almonds  peanut  cashewnut
price       20      10         25

In [42]:
weekly_sales["Total ($)"]=weekly_sales.dot(nuts_prices.T)

In [43]:
weekly_sales

almonds  peanut  cashewnut  Total ($)
mon        12       7          6        460
tue        15       9         12        690
wed         0      19          1        215
thur        3      18          6        390
fri         3       4          7        275

In [44]:
weekly_sales.describe()

almonds     peanut  cashewnut   Total ($)
count   5.000000   5.000000   5.000000    5.000000
mean    6.600000  11.400000   6.400000  406.000000
std     6.503845   6.730527   3.911521  185.384735
min     0.000000   4.000000   1.000000  215.000000
25%     3.000000   7.000000   6.000000  275.000000
50%     3.000000   9.000000   6.000000  390.000000
75%    12.000000  18.000000   7.000000  460.000000
max    15.000000  19.000000  12.000000  690.000000

In [45]:
prices.argmin()

1

In [46]:
prices.argsort()

array([[1, 0, 2]])

In [47]:
from matplotlib.image import imread


<img src="images/car-photo.png"/>

In [48]:
car=imread("images/car-photo.png")
car

array([[[0.5019608 , 0.50980395, 0.4862745 , 1.        ],
        [0.3372549 , 0.34509805, 0.30588236, 1.        ],
        [0.20392157, 0.21568628, 0.14901961, 1.        ],
        ...,
        [0.64705884, 0.7058824 , 0.54901963, 1.        ],
        [0.59607846, 0.63529414, 0.45882353, 1.        ],
        [0.44705883, 0.47058824, 0.3372549 , 1.        ]],

       [[0.44313726, 0.43529412, 0.40392157, 1.        ],
        [0.3137255 , 0.31764707, 0.27450982, 1.        ],
        [0.2       , 0.21176471, 0.14117648, 1.        ],
        ...,
        [0.5058824 , 0.5372549 , 0.4117647 , 1.        ],
        [0.49803922, 0.52156866, 0.39607844, 1.        ],
        [0.4       , 0.42745098, 0.34117648, 1.        ]],

       [[0.39607844, 0.38039216, 0.34117648, 1.        ],
        [0.31764707, 0.3137255 , 0.27450982, 1.        ],
        [0.28627452, 0.29411766, 0.24705882, 1.        ],
        ...,
        [0.44705883, 0.45882353, 0.32156864, 1.        ],
        [0.45882353, 0.482352

<img src="images/panda.png"/>

In [49]:
panda=imread("images/panda.png")

In [89]:
panda

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       ...,

       [[0.13333334, 0.07450981, 0.05490196],
        [0.12156863, 0.0627451 , 0.04313726],
        [0.10980392, 0

In [50]:
dog=imread("images/dog-photo.png")

<img src="images/dog-photo.png"/>

In [51]:
dog

array([[[0.70980394, 0.80784315, 0.88235295, 1.        ],
        [0.72156864, 0.8117647 , 0.8862745 , 1.        ],
        [0.7411765 , 0.8156863 , 0.8862745 , 1.        ],
        ...,
        [0.49803922, 0.6862745 , 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8352941 , 1.        ]],

       [[0.69411767, 0.8039216 , 0.8862745 , 1.        ],
        [0.7019608 , 0.8039216 , 0.88235295, 1.        ],
        [0.7058824 , 0.80784315, 0.88235295, 1.        ],
        ...,
        [0.5019608 , 0.6862745 , 0.84705883, 1.        ],
        [0.49411765, 0.68235296, 0.84313726, 1.        ],
        [0.49411765, 0.68235296, 0.8392157 , 1.        ]],

       [[0.6901961 , 0.8       , 0.88235295, 1.        ],
        [0.69803923, 0.8039216 , 0.88235295, 1.        ],
        [0.7058824 , 0.80784315, 0.88235295, 1.        ],
        ...,
        [0.5019608 , 0.6862745 , 0.84705883, 1.        ],
        [0.49803922, 0.686274